In [2]:
import  numpy as np
l1=[1,2,3,4,5]
x=np.array(l1)
print(x)
print("Type",type(x))
print("Dimension",x.ndim)

[1 2 3 4 5]
Type <class 'numpy.ndarray'>
Dimension 1


In [3]:
l1=[[1,2,3,4,5],[2,3,4,5,6]]
x=np.array(l1)
print(x)
print("Type",type(x))
print("Dimension",x.ndim)

[[1 2 3 4 5]
 [2 3 4 5 6]]
Type <class 'numpy.ndarray'>
Dimension 2


In [7]:
l1=[[[1,2,3,4,5],[2,3,4,5,6]],[[1,2,3,4,5],[2,3,4,5,6]]]
x1=np.array(l1)
print(x1)
print("Type",type(x1))
print("Dimension",x1.ndim)

[[[1 2 3 4 5]
  [2 3 4 5 6]]

 [[1 2 3 4 5]
  [2 3 4 5 6]]]
Type <class 'numpy.ndarray'>
Dimension 3


In [8]:
np.where(x>5)

(array([1], dtype=int64), array([4], dtype=int64))

In [9]:
np.sort(x1,axis=0)


array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]]])

In [10]:
np.sort(x1,axis=1)

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]]])

In [22]:
l1=[1,2,3,4,5,6]
x=np.array(l1)
x2=x1.reshape(4,-1)
print(x2)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [1 2 3 4 5]
 [2 3 4 5 6]]
